hyggg

diff --git a/jenkinsfiles/loadgenerator b/jenkinsfiles/loadgenerator
--- a/jenkinsfiles/loadgenerator
+++ b/jenkinsfiles/loadgenerator
@@ -47,32 +47,33 @@ pipeline {
             }
         }
 
-        stage('Update YAML & Git Push') {
-            steps {
-                dir('kubernetes-files') {
-                    withCredentials([string(credentialsId: 'my-git-pattoken', variable: 'GIT_TOKEN')]) {
-                        sh '''
-                            git config user.email "aymen.bendjaballah@univ-constantine2.dz"
-                            git config user.name "aymenmahrez-19"
+stage('Update YAML & Git Push') {
+    steps {
+        dir('kubernetes-files') {
+            withCredentials([string(credentialsId: 'my-git-pattoken', variable: 'GIT_TOKEN')]) {
+                sh '''
+                    git config user.email "aymen.bendjaballah@univ-constantine2.dz"
+                    git config user.name "aymenmahrez-19"
 
-                            YAML_FILE="loadgenerator.yaml"
+                    YAML_FILE="loadgenerator.yaml"
 
-                            if [ ! -f "$YAML_FILE" ]; then
-                              echo "❌ $YAML_FILE not found"
-                              exit 1
-                            fi
+                    if [ ! -f "$YAML_FILE" ]; then
+                      echo "❌ $YAML_FILE not found"
+                      exit 1
+                    fi
 
-                            sed -i "s#image:.*#image: ${ECR_REPO}:latest#g" $YAML_FILE
+                    sed -i "s#image:.*#image: 851725560519.dkr.ecr.us-east-1.amazonaws.com/aymen-load-generator:latest#g" $YAML_FILE
 
-                            git add $YAML_FILE
-                            git commit -m "Update load-generator image"
-                            git push https://${GIT_TOKEN}@github.com/aymenmahrez-19/Microservices-E-Commerce-eks-project.git master
-                        '''
-                    }
-                }
+                    git add $YAML_FILE
+                    git commit -m "Update load-generator image" || echo "No changes to commit"
+
+                    git push https://${GIT_TOKEN}@github.com/aymenmahrez-19/Microservices-E-Commerce-eks-project.git HEAD:master
+                '''
             }
         }
     }
+}
+
 
     post {
         success {
