yaml

diff --git a/jenkinsfiles/productcatalogservice b/jenkinsfiles/productcatalogservice
--- a/jenkinsfiles/productcatalogservice
+++ b/jenkinsfiles/productcatalogservice
@@ -54,29 +54,29 @@ pipeline {
             }
         }
 
-        stage('Update YAML & Git Push') {
-            steps {
-                dir('kubernetes-files') {
-                    withCredentials([string(credentialsId: 'my-git-pattoken', variable: 'GIT_TOKEN')]) {
-                        sh(script: """
-                            git config user.email "aymen.bendjaballah@univ-constantine2.dz"
-                            git config user.name "aymenmahrez-19"
-                            YAML_FILE="productcatalogservice.yaml"
-                            if [ -f "\${YAML_FILE}" ]; then
-                                sed -i 's#image:.*#image: ${ECR_REPO}:latest#g' "\${YAML_FILE}"
-                                git add "\${YAML_FILE}"
-                                git commit -m "Update image to latest"
-                                git push https://${GIT_TOKEN}@github.com/aymenmahrez-19/Microservices-E-Commerce-eks-project.git master
-                            else
-                                echo "❌ \${YAML_FILE} not found!"
-                                exit 1
-                            fi
-                        """)
-                    }
-                }
+stage('Update YAML & Git Push') {
+    steps {
+        dir('kubernetes-files') {
+            withCredentials([string(credentialsId: 'my-git-pattoken', variable: 'GIT_TOKEN')]) {
+                sh(script: """
+                    git config user.email "aymen.bendjaballah@univ-constantine2.dz"
+                    git config user.name "aymenmahrez-19"
+                    YAML_FILE="productcatalogservice.yaml"
+                    if [ -f "\${YAML_FILE}" ]; then
+                        sed -i 's#image:.*#image: ${ECR_REPO}:latest#g' "\${YAML_FILE}"
+                        git add "\${YAML_FILE}"
+                        git commit -m "Update image to latest"
+                        git push https://${GIT_TOKEN}@github.com/aymenmahrez-19/Microservices-E-Commerce-eks-project.git master
+                    else
+                        echo "❌ \${YAML_FILE} not found!"
+                        exit 1
+                    fi
+                """)
             }
         }
     }
+}
+
 
     post {
         success {
